// ============================================================
// NMU i18n — Network Marketing Ultimate Translations
// TR (Turkish) & EN (American English)
// ============================================================

export type Locale = 'en' | 'tr'

export const translations = {
  en: {
    nav: { dashboard: 'Dashboard', prospects: 'Prospects', contacts: 'Contacts', customers: 'Customers', pipeline: 'Pipeline', tasks: 'Tasks & Follow-ups', academy: 'Academy', scripts: 'Scripts & Content Vault', events: 'Events', team: 'Team / Organization', analytics: 'Analytics', aiCoach: 'AI Coach', automations: 'Automations', admin: 'Admin', settings: 'Settings', notifications: 'Notifications' },
    common: { search: 'Search contacts, scripts, courses...', add: 'Add', save: 'Save', cancel: 'Cancel', delete: 'Delete', edit: 'Edit', view: 'View', viewAll: 'View all', back: 'Back', next: 'Next', previous: 'Previous', loading: 'Loading...', noData: 'No data available', active: 'Active', inactive: 'Inactive', completed: 'Completed', pending: 'Pending', overdue: 'Overdue', today: 'Today', yesterday: 'Yesterday', thisWeek: 'This Week', thisMonth: 'This Month', all: 'All', filter: 'Filter', export: 'Export', import: 'Import', copy: 'Copy', copied: 'Copied!', create: 'Create', manage: 'Manage', launch: 'Launch', urgent: 'Urgent', high: 'High', medium: 'Medium', low: 'Low', saveChanges: 'Save Changes', managePlan: 'Manage Plan', backToContacts: 'Back to Contacts', call: 'Call', message: 'Message', msg: 'Msg', markAllRead: 'Mark all read', quickActions: 'Quick Actions', addNewProspect: 'Add new contact', createTask: 'Create task', startAISession: 'Start AI session', viewTodaysPipeline: "View today's pipeline", viewAllNotifications: 'View all notifications', noInteractionsYet: 'No interactions yet', logFirstInteraction: 'Log First Interaction', tasksFor: 'Tasks for', noTasksForContact: 'No tasks for this contact', due: 'Due', pipelineStage: 'Pipeline Stage', relationship: 'Relationship', tags: 'Tags', family: 'Family', goals: 'Goals', interactionHistory: 'Interaction History', orders: 'Orders', totalSpent: 'Total Spent', loyalty: 'Loyalty', recentOrders: 'Recent Orders', productCatalog: 'Product Catalog', trigger: 'Trigger', actions: 'actions', run: 'Run', times: 'times', lastRun: 'Last run', paused: 'Paused', level: 'Level', progressTo: 'progress to', requirements: 'requirements', benefits: 'benefits', current: 'Current', achieved: 'Achieved', contactsMade: 'Contacts Made', followUps: 'Follow-ups', presentations: 'Presentations', newLeads: 'New Leads', member: 'Member', mon: 'Mon', tue: 'Tue', wed: 'Wed', thu: 'Thu', fri: 'Fri', sat: 'Sat', sun: 'Sun', smartInsights: 'Smart Insights', loadingNMU: 'Loading NMU...', dayStreak: 'Day Streak', hot: 'Hot', confirmed: 'confirmed', createNewEvent: 'Create New Event', schedulePresentation: 'Schedule a presentation, training, or team call', virtualMeeting: 'Virtual Meeting', progress: 'Progress', onboarding: 'Onboarding', lastActive: 'Last active', pipeline: 'pipeline', activity: 'Activity', streak: 'Streak', momentum: 'Momentum' },
    dashboard: { title: 'Command Center', greeting: 'Good morning', streak: 'Day Streak', momentum: 'Momentum', dailyFocus: 'Daily Focus', todaysFocus: "Today's Focus", quickActions: 'Quick Actions', logCall: 'Log Call', addProspect: 'Add Prospect', bookPresentation: 'Book Presentation', askAI: 'Ask AI', kpi: { newLeads: 'New Leads', followUps: 'Follow-ups', presentations: 'Presentations', conversions: 'Conversions', customers: 'Customers', team: 'Team', training: 'Training' }, pipelineOverview: 'Pipeline Overview', weeklyActivity: 'Weekly Activity', aiRecommendations: 'AI Recommendations', hotLeads: 'Hot Leads', teamPulse: 'Team Pulse', upcomingEvents: 'Upcoming Events', tasksDue: 'tasks due today', hotLeadsWaiting: 'hot leads waiting', momentumStrong: 'Your momentum is strong — keep pushing.', today: 'Today', booked: 'booked', invited: 'invited', confirmed: 'confirmed', viewAllTasks: 'view all tasks', viewTeam: 'View team', activity: 'activity', orders: 'Orders', totalSpent: 'Total Spent', loyalty: 'Loyalty', recentOrders: 'Recent Orders', xpReward: 'XP', day23Streak: 'Day 23 Streak 🔥' },
    prospects: { title: 'Prospects', subtitle: 'contacts in your pipeline', addProspect: 'Add Prospect', importContacts: 'Import', exportContacts: 'Export', searchPlaceholder: 'Search prospects...', allStages: 'All Stages', hotLeads: 'Hot Leads', warmLeads: 'Warm Leads', coldLeads: 'Cold Leads', contact: 'Contact', stage: 'Stage', temperature: 'Temperature', interest: 'Interest', lastContact: 'Last Contact', nextFollowUp: 'Next Follow-up', actions: 'Actions', call: 'Call', message: 'Message', email: 'Email' },
    pipeline: { title: 'Pipeline', subtitle: 'Drag contacts between stages to update their journey', addToPipeline: 'Add to Pipeline', dropHere: 'Drop contacts here', stages: { new: 'New Lead', contactPlanned: 'Contact Planned', firstContact: 'First Contact', interested: 'Interested', invited: 'Invited', presentationSent: 'Presentation Sent', followupPending: 'Follow-up Pending', objectionHandling: 'Objection Handling', readyToBuy: 'Ready to Buy', becameCustomer: 'Customer', readyToJoin: 'Ready to Join', becameMember: 'Team Member', nurtureLater: 'Nurture Later', dormant: 'Dormant', lost: 'Lost' } },
    tasks: { title: 'Tasks & Follow-ups', subtitle: 'pending tasks', createTask: 'Create Task', allTasks: 'All', pendingTasks: 'Pending', completedTasks: 'Completed', overdueTasks: 'Overdue', priority: { urgent: 'Urgent', high: 'High', medium: 'Medium', low: 'Low' }, types: { followUp: 'Follow-up', call: 'Call', meeting: 'Meeting', presentation: 'Presentation', onboarding: 'Onboarding', training: 'Training', custom: 'Custom' } },
    contacts: { title: 'Contacts', subtitle: 'contacts in your operating workspace', addContact: 'Add Contact', searchPlaceholder: 'Search contacts...', profile: 'Profile', pipelineStage: 'Pipeline Stage', relationship: 'Relationship', tags: 'Tags', family: 'Family', goals: 'Goals', interactionHistory: 'Interaction History', noInteractions: 'No interactions yet', logFirstInteraction: 'Log First Interaction', tasksFor: 'Tasks for', noTasks: 'No tasks for this contact' },
    customers: { title: 'Customers', subtitle: 'active customers', addCustomer: 'Add Customer', activeCustomers: 'Active Customers', totalRevenue: 'Total Revenue', avgOrder: 'Avg Order', reordersDue: 'Reorders Due', orders: 'Orders', totalSpent: 'Total Spent', loyalty: 'Loyalty', recentOrders: 'Recent Orders', productCatalog: 'Product Catalog' },
    academy: { title: 'Academy', subtitle: 'Master every skill to build a thriving business', courses: 'Courses', completed: 'Completed', xpEarned: 'XP Earned', certifications: 'Certifications', yourLearningPath: 'Your Learning Path', lessons: 'lessons', progress: 'Progress', achievements: 'Achievements', backToCourses: 'Back to Courses', watch: 'Watch', start: 'Start', begin: 'Begin', levels: { beginner: 'Beginner', intermediate: 'Intermediate', advanced: 'Advanced', leader: 'Leader' } },
    team: { title: 'Team', subtitle: 'members in your organization', inviteMember: 'Invite Member', totalMembers: 'Total Members', activeMembers: 'Active', atRisk: 'At Risk', avgActivity: 'Avg Activity', activity: 'Activity', streak: 'Streak', momentum: 'Momentum', onboarding: 'Onboarding', pipelineHealth: { strong: 'Strong', moderate: 'Moderate', weak: 'Weak', critical: 'Critical' }, riskLevel: { low: 'Low', medium: 'Medium', high: 'High' }, duplicationToolkit: 'Duplication Toolkit', launchChecklist: 'Launch Checklist', scriptPacks: 'Script Packs', onboardingTemplates: 'Onboarding Templates', teamMeetingKit: 'Team Meeting Kit', first48h: 'First 48h plan', inviteFollowUp: 'Invite & Follow-up', newMemberFlow: 'New member flow', weeklyCallGuide: 'Weekly call guide' },
    analytics: { title: 'Analytics', subtitle: 'Performance insights and growth metrics', contactRate: 'Contact Rate', presentationRate: 'Presentation Rate', customerConv: 'Customer Conv.', recruitConv: 'Recruit Conv.', reorderRate: 'Reorder Rate', onboardingRate: 'Onboarding', weeklyActivity: 'Weekly Activity', monthlyTrend: 'Monthly Conversion Trend', pipelineDist: 'Pipeline Distribution', teamHeatmap: 'Team Activity Heatmap', conversionFunnel: 'Conversion Funnel', totalLeads: 'Total Leads', contacted: 'Contacted', interested: 'Interested', presented: 'Presented', converted: 'Converted' },
    ai: { title: 'AI Growth Coach', subtitle: 'Your intelligent business strategist', capabilities: { nextBestAction: 'Next-Best Action', nextBestActionDesc: 'Get intelligent suggestions for who to contact and what to say', messageDrafting: 'Message Drafting', messageDraftingDesc: 'AI-powered invitation and follow-up message creation', leadScoring: 'Lead Scoring', leadScoringDesc: 'Predictive heat scoring based on engagement patterns', pipelineAnalysis: 'Pipeline Analysis', pipelineAnalysisDesc: 'Detect stagnation and suggest pipeline interventions', courseRecommendations: 'Course Recommendations', courseRecommendationsDesc: 'Personalized learning path based on your business stage', weeklyReview: 'Weekly Business Review', weeklyReviewDesc: 'Automated performance summaries with actionable insights' }, todaysInsights: "Today's Smart Insights", chatWithAI: 'Chat with AI Coach', chatPlaceholder: 'Ask your AI coach anything...', confidence: 'confidence' },
    events: { title: 'Events', subtitle: 'Manage presentations, trainings, and team gatherings', createEvent: 'Create Event', types: { onlinePresentation: 'Online Presentation', homeMeeting: 'Home Meeting', teamZoom: 'Team Zoom', training: 'Training', workshop: 'Workshop', local: 'Local Event', regional: 'Regional Event', global: 'Global Event' }, confirmed: 'confirmed', invited: 'invited', virtualMeeting: 'Virtual Meeting', status: { published: 'Published', draft: 'Draft', cancelled: 'Cancelled' }, triggerTypes: { stage_change: 'Stage Change', task_overdue: 'Task Overdue', date_reached: 'Date Reached', inactivity: 'Inactivity', order_placed: 'Order Placed', course_completed: 'Course Completed', event_attended: 'Event Attended', manual: 'Manual' } },
    scripts: { title: 'Scripts & Content Vault', subtitle: 'Battle-tested scripts for every situation', allScripts: 'All Scripts', categories: { invitation: 'Invitation', followUp: 'Follow-up', customerCare: 'Customer Care', socialMedia: 'Social Media', onboarding: 'Onboarding', objections: 'Objections', prospecting: 'Prospecting' }, uses: 'uses', copy: 'Copy', objectionHandling: 'Objection Handling Library' },
    automations: { title: 'Automation Center', subtitle: 'Set up intelligent workflows that run on autopilot', createAutomation: 'Create Automation', active: 'Active', totalRuns: 'Total Runs', thisWeek: 'This Week', templates: 'Templates', automationTemplates: 'Automation Templates', templateNames: { welcome: 'Welcome Sequence', welcomeDesc: 'New lead onboarding', reorder: 'Reorder Reminder', reorderDesc: 'Customer retention', inactivity: 'Inactivity Alert', inactivityDesc: 'Team member check-in', eventFollowup: 'Event Follow-up', eventFollowupDesc: 'Post-event conversion' } },
    admin: { title: 'Admin Panel', subtitle: 'System configuration and management', totalUsers: 'Total Users', activeToday: 'Active Today', contentItems: 'Content Items', sections: { userManagement: 'User Management', userManagementDesc: 'Manage users, roles, and permissions', contentManagement: 'Content Management', contentManagementDesc: 'Manage academy knowledge, objection guides, and templates', systemSettings: 'System Settings', systemSettingsDesc: 'Configure platform settings', security: 'Security', securityDesc: 'Security and compliance settings', analyticsReports: 'Analytics & Reports', analyticsReportsDesc: 'System-wide analytics', localization: 'Localization', localizationDesc: 'Language and regional settings' }, items: { userDirectory: 'User Directory', roleAssignment: 'Role Assignment', teamStructure: 'Team Structure', accessLogs: 'Access Logs', academyCourses: 'Academy Courses', scriptLibrary: 'Content Library', emailTemplates: 'Objection Bank', campaignAssets: 'Event Assets', generalSettings: 'General Settings', emailConfig: 'Email Configuration', apiKeys: 'API Keys', integrations: 'Integrations', authentication: 'Authentication', dataPrivacy: 'Data Privacy', auditLogs: 'Audit Logs', compliance: 'Compliance', usageAnalytics: 'Usage Analytics', performanceReports: 'Performance Reports', exportData: 'Export Data', customReports: 'Custom Reports', languages: 'Languages', translations: 'Translations', regionalSettings: 'Regional Settings', currency: 'Currency' } },
    settings: { title: 'Settings', subtitle: 'Manage your profile and preferences', profile: 'Profile', changePhoto: 'Change Photo', fullName: 'Full Name', email: 'Email', timezone: 'Timezone', language: 'Language', saveChanges: 'Save Changes', appearance: 'Appearance', theme: 'Theme', dark: 'Dark', light: 'Light', system: 'System', reducedMotion: 'Reduced Motion', reducedMotionDesc: 'Minimize animations', notifications: 'Notifications', followUpReminders: 'Follow-up Reminders', followUpRemindersDesc: 'Get notified when follow-ups are due', teamAlerts: 'Team Alerts', teamAlertsDesc: 'Notifications about team member activity', aiSuggestions: 'AI Suggestions', aiSuggestionsDesc: 'Smart recommendations from AI coach', eventReminders: 'Event Reminders', eventRemindersDesc: 'Reminders for upcoming events', achievementUnlocks: 'Achievement Unlocks', achievementUnlocksDesc: 'Celebrate your milestones', weeklySummary: 'Weekly Summary', weeklySummaryDesc: 'Weekly performance digest', aiPreferences: 'AI Preferences', aiSuggestionsToggle: 'AI Suggestions', aiSuggestionsToggleDesc: 'Enable AI-powered recommendations', dailyGoalReminders: 'Daily Goal Reminders', dailyGoalRemindersDesc: 'AI reminds you of daily targets', aiCoachingStyle: 'AI Coaching Style', encouraging: 'Encouraging', direct: 'Direct', analytical: 'Analytical', subscription: 'Subscription', proPlan: 'Pro Plan', managePlan: 'Manage Plan', renews: 'Renews', planFeatures: 'Unlimited contacts, AI coach, academy access' },
    notificationsPage: { title: 'Notifications', subtitle: 'unread notifications', markAllRead: 'Mark all as read', unread: 'Unread', earlier: 'Earlier', types: { followUpDue: 'Follow-up Due', teamAlert: 'Team Alert', achievement: 'Achievement Unlocked!', aiSuggestion: 'AI Insight', eventReminder: 'Event Reminder', system: 'System' } },
    header: { streak: 'streak', momentum: 'momentum', aiCoach: 'AI Coach' },
    sidebar: { operatingSystem: 'Operating System', goldDirector: 'Gold Director', logout: 'Sign Out' },
    temperature: { hot: 'Hot', warm: 'Warm', cold: 'Cold', frozen: 'Frozen' },
    interest: { product: 'Product', business: 'Business', both: 'Both', unknown: 'Unknown' },
    status: { active: 'Active', published: 'Published', draft: 'Draft', completed: 'Completed', cancelled: 'Cancelled', delivered: 'Delivered', shipped: 'Shipped', pending: 'Pending', confirmed: 'Confirmed' },
    auth: { login: 'Sign In', signup: 'Create Account', email: 'Email', password: 'Password', fullName: 'Full Name', passwordPlaceholder: '••••••••', emailPlaceholder: 'name@example.com', signInBtn: 'Sign In', signUpBtn: 'Create Account', signingIn: 'Signing in...', creatingAccount: 'Creating account...', noAccount: "Don't have an account?", hasAccount: 'Already have an account?', createAccount: 'Create Account', signIn: 'Sign In', tagline: 'Run your entire network marketing business from one intelligent system.' },
  },

  tr: {
    nav: { dashboard: 'Kontrol Paneli', prospects: 'Potansiyel Müşteriler', contacts: 'Kontaklar', customers: 'Müşteriler', pipeline: 'Süreç Takibi', tasks: 'Görevler & Takipler', academy: 'Akademi', scripts: 'Senaryo & İçerik Havuzu', events: 'Etkinlikler', team: 'Ekip / Organizasyon', analytics: 'Analitik', aiCoach: 'YZ Koçu', automations: 'Otomasyonlar', admin: 'Yönetici', settings: 'Ayarlar', notifications: 'Bildirimler' },
    common: { search: 'Kişi, senaryo, kurs ara...', add: 'Ekle', save: 'Kaydet', cancel: 'İptal', delete: 'Sil', edit: 'Düzenle', view: 'Görüntüle', viewAll: 'Tümünü Gör', back: 'Geri', next: 'İleri', previous: 'Önceki', loading: 'Yükleniyor...', noData: 'Veri bulunamadı', active: 'Aktif', inactive: 'Pasif', completed: 'Tamamlandı', pending: 'Bekliyor', overdue: 'Gecikmiş', today: 'Bugün', yesterday: 'Dün', thisWeek: 'Bu Hafta', thisMonth: 'Bu Ay', all: 'Tümü', filter: 'Filtrele', export: 'Dışa Aktar', import: 'İçe Aktar', copy: 'Kopyala', copied: 'Kopyalandı!', create: 'Oluştur', manage: 'Yönet', launch: 'Başlat', urgent: 'Acil', high: 'Yüksek', medium: 'Orta', low: 'Düşük', saveChanges: 'Değişiklikleri Kaydet', managePlan: 'Planı Yönet', backToContacts: 'Kontaklara Dön', call: 'Ara', message: 'Mesaj', msg: 'Mesaj', markAllRead: 'Tümünü okundu işaretle', quickActions: 'Hızlı İşlemler', addNewProspect: 'Yeni kontak ekle', createTask: 'Görev oluştur', startAISession: 'AI oturumu başlat', viewTodaysPipeline: 'Bugünün hunisini görüntüle', viewAllNotifications: 'Tüm bildirimleri görüntüle', noInteractionsYet: 'Henüz iletişim kaydı yok', logFirstInteraction: 'İlk İletişimi Kaydet', tasksFor: 'Görevler', noTasksForContact: 'Bu kontak için görev yok', due: 'Son Tarih', pipelineStage: 'Huni Aşaması', relationship: 'İlişki', tags: 'Etiketler', family: 'Aile', goals: 'Hedefler', interactionHistory: 'İletişim Geçmişi', orders: 'Siparişler', totalSpent: 'Toplam Harcama', loyalty: 'Sadakat', recentOrders: 'Son Siparişler', productCatalog: 'Ürün Kataloğu', trigger: 'Tetikleyici', actions: 'aksiyon', run: 'Çalışma', times: 'kez', lastRun: 'Son çalışma', paused: 'Duraklatıldı', level: 'Seviye', progressTo: 'ilerleme', requirements: 'gereksinimler', benefits: 'avantaj', current: 'Mevcut', achieved: 'Kazanıldı', contactsMade: 'İletişim Kurulan', followUps: 'Takipler', presentations: 'Sunumlar', newLeads: 'Yeni Potansiyel', member: 'Üye', mon: 'Pzt', tue: 'Sal', wed: 'Çar', thu: 'Per', fri: 'Cum', sat: 'Cmt', sun: 'Paz', smartInsights: 'Akıllı İçgörüler', loadingNMU: 'NMU Yükleniyor...', dayStreak: 'Gün Serisi', hot: 'Sıcak', confirmed: 'onaylandı', createNewEvent: 'Yeni Etkinlik Oluştur', schedulePresentation: 'Bir sunum, eğitim veya ekip görüşmesi planla', virtualMeeting: 'Sanal Toplantı', progress: 'İlerleme', onboarding: 'Oryantasyon', lastActive: 'Son aktif', pipeline: 'huni', activity: 'Aktivite', streak: 'Seri', momentum: 'İvme' },
    dashboard: { title: 'Komuta Merkezi', greeting: 'Merhaba', streak: 'Gün Serisi', momentum: 'İvme', dailyFocus: 'Günlük Odak', todaysFocus: 'Bugünün Odak Noktaları', quickActions: 'Hızlı İşlemler', logCall: 'Arama Kaydet', addProspect: 'Potansiyel Ekle', bookPresentation: 'Sunum Planla', askAI: 'AI\'ya Sor', kpi: { newLeads: 'Yeni Potansiyel', followUps: 'Takipler', presentations: 'Sunumlar', conversions: 'Dönüşümler', customers: 'Müşteriler', team: 'Ekip', training: 'Eğitim' }, pipelineOverview: 'Süreç Takibi Genel Bakış', weeklyActivity: 'Haftalık Aktivite', aiRecommendations: 'AI Önerileri', hotLeads: 'Sıcak Potansiyeller', teamPulse: 'Ekip Nabzı', upcomingEvents: 'Yaklaşan Etkinlikler', tasksDue: 'bugün yapılacak görev', hotLeadsWaiting: 'sıcak potansiyel bekliyor', momentumStrong: 'İvmen güçlü — böyle devam et.', today: 'Bugün', booked: 'planlandı', invited: 'davet edildi', confirmed: 'onaylandı', viewAllTasks: 'tüm görevleri görüntüle', viewTeam: 'ekibi görüntüle', activity: 'aktivite', orders: 'Siparişler', totalSpent: 'Toplam Harcama', loyalty: 'Sadakat', recentOrders: 'Son Siparişler', xpReward: 'XP', day23Streak: '23 Gün Serisi 🔥' },
    prospects: { title: 'Potansiyel Müşteriler', subtitle: 'kişi sürecinizde', addProspect: 'Potansiyel Ekle', importContacts: 'İçe Aktar', exportContacts: 'Dışa Aktar', searchPlaceholder: 'Potansiyel ara...', allStages: 'Tüm Aşamalar', hotLeads: 'Sıcak Potansiyeller', warmLeads: 'Ilık Potansiyeller', coldLeads: 'Soğuk Potansiyeller', contact: 'Kişi', stage: 'Aşama', temperature: 'Sıcaklık', interest: 'İlgi', lastContact: 'Son İletişim', nextFollowUp: 'Sonraki Takip', actions: 'İşlemler', call: 'Ara', message: 'Mesaj', email: 'E-posta' },
    pipeline: { title: 'Süreç Takibi', subtitle: 'Kişileri aşamalar arasında sürükleyerek yolculuklarını güncelle', addToPipeline: 'Sürece Ekle', dropHere: 'Kişileri buraya bırakın', stages: { new: 'Yeni Potansiyel', contactPlanned: 'İletişim Planlandı', firstContact: 'İlk İletişim', interested: 'İlgileniyor', invited: 'Davet Edildi', presentationSent: 'Sunum Gönderildi', followupPending: 'Takip Bekleniyor', objectionHandling: 'İtiraz Yönetimi', readyToBuy: 'Satın Almaya Hazır', becameCustomer: 'Müşteri Oldu', readyToJoin: 'Katılmaya Hazır', becameMember: 'Ekip Üyesi', nurtureLater: 'Sonra İlgilen', dormant: 'Pasif', lost: 'Kaybedildi' } },
    tasks: { title: 'Görevler & Takipler', subtitle: 'bekleyen görev', createTask: 'Görev Oluştur', allTasks: 'Tümü', pendingTasks: 'Bekleyen', completedTasks: 'Tamamlanan', overdueTasks: 'Gecikmiş', priority: { urgent: 'Acil', high: 'Yüksek', medium: 'Orta', low: 'Düşük' }, types: { followUp: 'Takip', call: 'Arama', meeting: 'Toplantı', presentation: 'Sunum', onboarding: 'Oryantasyon', training: 'Eğitim', custom: 'Özel' } },
    contacts: { title: 'Kontaklar', subtitle: 'tek kontak merkezinizde', addContact: 'Kontak Ekle', searchPlaceholder: 'Kontak ara...', profile: 'Profil', pipelineStage: 'Huni Aşaması', relationship: 'İlişki', tags: 'Etiketler', family: 'Aile', goals: 'Hedefler', interactionHistory: 'İletişim Geçmişi', noInteractions: 'Henüz iletişim kaydı yok', logFirstInteraction: 'İlk İletişimi Kaydet', tasksFor: 'Görevler', noTasks: 'Bu kontak için görev yok' },
    customers: { title: 'Müşteriler', subtitle: 'aktif müşteri', addCustomer: 'Müşteri Ekle', activeCustomers: 'Aktif Müşteriler', totalRevenue: 'Toplam Gelir', avgOrder: 'Ort. Sipariş', reordersDue: 'Yeniden Sipariş', orders: 'Siparişler', totalSpent: 'Toplam Harcama', loyalty: 'Sadakat', recentOrders: 'Son Siparişler', productCatalog: 'Ürün Kataloğu' },
    academy: { title: 'Akademi', subtitle: 'Başarılı bir iş kurmak için her beceriyi öğren', courses: 'Kurslar', completed: 'Tamamlanan', xpEarned: 'Kazanılan XP', certifications: 'Sertifikalar', yourLearningPath: 'Öğrenme Yolculuğun', lessons: 'ders', progress: 'İlerleme', achievements: 'Başarılar', backToCourses: 'Kurslara Dön', watch: 'İzle', start: 'Başla', begin: 'Başla', levels: { beginner: 'Başlangıç', intermediate: 'Orta Seviye', advanced: 'İleri Seviye', leader: 'Lider' } },
    team: { title: 'Ekip', subtitle: 'üye organizasyonunuzda', inviteMember: 'Üye Davet Et', totalMembers: 'Toplam Üye', activeMembers: 'Aktif', atRisk: 'Risk Altında', avgActivity: 'Ort. Aktivite', activity: 'Aktivite', streak: 'Seri', momentum: 'İvme', onboarding: 'Oryantasyon', pipelineHealth: { strong: 'Güçlü', moderate: 'Orta', weak: 'Zayıf', critical: 'Kritik' }, riskLevel: { low: 'Düşük', medium: 'Orta', high: 'Yüksek' }, duplicationToolkit: 'Çoğaltma Araç Seti', launchChecklist: 'Başlangıç Kontrol Listesi', scriptPacks: 'Senaryo Paketleri', onboardingTemplates: 'Oryantasyon Şablonları', teamMeetingKit: 'Ekip Toplantı Kiti', first48h: 'İlk 48 saat planı', inviteFollowUp: 'Davet & Takip', newMemberFlow: 'Yeni üye akışı', weeklyCallGuide: 'Haftalık çağrı rehberi' },
    analytics: { title: 'Analitik', subtitle: 'Performans içgörüleri ve büyüme metrikleri', contactRate: 'İletişim Oranı', presentationRate: 'Sunum Oranı', customerConv: 'Müşteri Dönüşümü', recruitConv: 'Üye Dönüşümü', reorderRate: 'Yeniden Sipariş', onboardingRate: 'Oryantasyon', weeklyActivity: 'Haftalık Aktivite', monthlyTrend: 'Aylık Dönüşüm Trendi', pipelineDist: 'Huni Dağılımı', teamHeatmap: 'Ekip Aktivite Haritası', conversionFunnel: 'Dönüşüm Hunisi', totalLeads: 'Toplam Potansiyel', contacted: 'İletişime Geçildi', interested: 'İlgileniyor', presented: 'Sunum Yapıldı', converted: 'Dönüştü' },
    ai: { title: 'AI Büyüme Koçu', subtitle: 'Akıllı iş stratejistin', capabilities: { nextBestAction: 'Sonraki En İyi Aksiyon', nextBestActionDesc: 'Kiminle iletişime geçeceğini ve ne söyleyeceğini akıllı öneriler al', messageDrafting: 'Mesaj Taslağı', messageDraftingDesc: 'AI destekli davet ve takip mesajı oluşturma', leadScoring: 'Potansiyel Puanlama', leadScoringDesc: 'Etkileşim kalıplarına dayalı tahmini sıcaklık puanlaması', pipelineAnalysis: 'Huni Analizi', pipelineAnalysisDesc: 'Durgunluğu tespit et ve huni müdahaleleri öner', courseRecommendations: 'Kurs Önerileri', courseRecommendationsDesc: 'İş aşamana göre kişiselleştirilmiş öğrenme yolu', weeklyReview: 'Haftalık İş Değerlendirmesi', weeklyReviewDesc: 'Aksiyon alınabilir içgörülerle otomatik performans özetleri' }, todaysInsights: 'Günün Akıllı İçgörüleri', chatWithAI: 'AI Koç ile Sohbet', chatPlaceholder: 'AI koçuna her şeyi sor...', confidence: 'güven' },
    events: { title: 'Etkinlikler', subtitle: 'Sunumları, eğitimleri ve ekip buluşmalarını yönet', createEvent: 'Etkinlik Oluştur', types: { onlinePresentation: 'Online Sunum', homeMeeting: 'Ev Toplantısı', teamZoom: 'Ekip Zoom', training: 'Eğitim', workshop: 'Atölye', local: 'Yerel Etkinlik', regional: 'Bölgesel Etkinlik', global: 'Küresel Etkinlik' }, confirmed: 'onaylandı', invited: 'davet edildi', virtualMeeting: 'Sanal Toplantı', status: { published: 'Yayında', draft: 'Taslak', cancelled: 'İptal Edildi' }, triggerTypes: { stage_change: 'Aşama Değişikliği', task_overdue: 'Gorev Gecikti', date_reached: 'Tarih Geldi', inactivity: 'Hareketsizlik', order_placed: 'Siparis Verildi', course_completed: 'Kurs Tamamlandi', event_attended: 'Etkinlige Katildi', manual: 'Manuel' } },
    scripts: { title: 'Senaryo & İçerik Havuzu', subtitle: 'Her durum için test edilmiş senaryolar', allScripts: 'Tüm Senaryolar', categories: { invitation: 'Davet', followUp: 'Takip', customerCare: 'Müşteri İlişkileri', socialMedia: 'Sosyal Medya', onboarding: 'Oryantasyon', objections: 'İtirazlar', prospecting: 'Potansiyel Müşteri' }, uses: 'kullanım', copy: 'Kopyala', objectionHandling: 'İtiraz Yönetimi Kütüphanesi' },
    automations: { title: 'Otomasyon Merkezi', subtitle: 'Otomatik çalışan akıllı iş akışları oluştur', createAutomation: 'Otomasyon Oluştur', active: 'Aktif', totalRuns: 'Toplam Çalışma', thisWeek: 'Bu Hafta', templates: 'Şablonlar', automationTemplates: 'Otomasyon Şablonları', templateNames: { welcome: 'Karşılama Sekansı', welcomeDesc: 'Yeni potansiyel oryantasyonu', reorder: 'Yeniden Sipariş Hatırlatması', reorderDesc: 'Müşteri sadakati', inactivity: 'İnaktivite Uyarısı', inactivityDesc: 'Ekip üyesi kontrolü', eventFollowup: 'Etkinlik Takibi', eventFollowupDesc: 'Etkinlik sonrası dönüşüm' } },
    admin: { title: 'Yönetici Paneli', subtitle: 'Sistem yapılandırması ve yönetimi', totalUsers: 'Toplam Kullanıcı', activeToday: 'Bugün Aktif', contentItems: 'İçerik Öğeleri', sections: { userManagement: 'Kullanıcı Yönetimi', userManagementDesc: 'Kullanıcıları, rolleri ve izinleri yönet', contentManagement: 'İçerik Yönetimi', contentManagementDesc: 'Akademi bilgisi, itiraz rehberleri ve şablonları yönet', systemSettings: 'Sistem Ayarları', systemSettingsDesc: 'Platform ayarlarını yapılandır', security: 'Güvenlik', securityDesc: 'Güvenlik ve uyumluluk ayarları', analyticsReports: 'Analitik & Raporlar', analyticsReportsDesc: 'Sistem geneli analitik', localization: 'Yerelleştirme', localizationDesc: 'Dil ve bölgesel ayarlar' }, items: { userDirectory: 'Kullanıcı Dizini', roleAssignment: 'Rol Atama', teamStructure: 'Ekip Yapısı', accessLogs: 'Erişim Kayıtları', academyCourses: 'Akademi Kursları', scriptLibrary: 'İçerik Kütüphanesi', emailTemplates: 'İtiraz Bankası', campaignAssets: 'Etkinlik Varlıkları', generalSettings: 'Genel Ayarlar', emailConfig: 'E-posta Yapılandırması', apiKeys: 'API Anahtarları', integrations: 'Entegrasyonlar', authentication: 'Kimlik Doğrulama', dataPrivacy: 'Veri Gizliliği', auditLogs: 'Denetim Kayıtları', compliance: 'Uyumluluk', usageAnalytics: 'Kullanım Analitiği', performanceReports: 'Performans Raporları', exportData: 'Veri Dışa Aktar', customReports: 'Özel Raporlar', languages: 'Diller', translations: 'Çeviriler', regionalSettings: 'Bölgesel Ayarlar', currency: 'Para Birimi' } },
    settings: { title: 'Ayarlar', subtitle: 'Profilini ve tercihlerini yönet', profile: 'Profil', changePhoto: 'Fotoğrafı Değiştir', fullName: 'Ad Soyad', email: 'E-posta', timezone: 'Saat Dilimi', language: 'Dil', appearance: 'Görünüm', theme: 'Tema', dark: 'Koyu', light: 'Açık', system: 'Sistem', reducedMotion: 'Azaltılmış Hareket', reducedMotionDesc: 'Animasyonları minimize et', notifications: 'Bildirimler', followUpReminders: 'Takip Hatırlatmaları', followUpRemindersDesc: 'Takipler geldiğinde bildirim al', teamAlerts: 'Ekip Uyarıları', teamAlertsDesc: 'Ekip üyesi aktivite bildirimleri', aiSuggestions: 'AI Önerileri', aiSuggestionsDesc: 'AI koçundan akıllı öneriler', eventReminders: 'Etkinlik Hatırlatmaları', eventRemindersDesc: 'Yaklaşan etkinlikler için hatırlatmalar', achievementUnlocks: 'Başarı Kilidi Açma', achievementUnlocksDesc: 'Kilometre taşlarını kutla', weeklySummary: 'Haftalık Özet', weeklySummaryDesc: 'Haftalık performans özeti', aiPreferences: 'AI Tercihleri', aiSuggestionsToggle: 'AI Önerileri', aiSuggestionsToggleDesc: 'AI destekli önerileri etkinleştir', dailyGoalReminders: 'Günlük Hedef Hatırlatmaları', dailyGoalRemindersDesc: 'AI günlük hedeflerini hatırlatır', aiCoachingStyle: 'AI Koçluk Stili', encouraging: 'Teşvik Edici', direct: 'Doğrudan', analytical: 'Analitik', subscription: 'Abonelik', proPlan: 'Pro Plan', renews: 'Yenileme', planFeatures: 'Sınırsız kişi, AI koç, akademi erişimi' },
    notificationsPage: { title: 'Bildirimler', subtitle: 'okunmamış bildirim', markAllRead: 'Tümünü okundu işaretle', unread: 'Okunmamış', earlier: 'Daha Önce', types: { followUpDue: 'Takip Zamanı', teamAlert: 'Ekip Uyarısı', achievement: 'Başarı Kilidi Açıldı!', aiSuggestion: 'AI İçgörüsü', eventReminder: 'Etkinlik Hatırlatması', system: 'Sistem' } },
    header: { streak: 'seri', momentum: 'ivme', aiCoach: 'YZ Koçu' },
    sidebar: { operatingSystem: 'İşletim Sistemi', goldDirector: 'Altın Direktör', logout: 'Çıkış Yap' },
    temperature: { hot: 'Sıcak', warm: 'Ilık', cold: 'Soğuk', frozen: 'Donuk' },
    interest: { product: 'Ürün', business: 'İş', both: 'Her İkisi', unknown: 'Bilinmiyor' },
    status: { active: 'Aktif', published: 'Yayında', draft: 'Taslak', completed: 'Tamamlandı', cancelled: 'İptal', delivered: 'Teslim Edildi', shipped: 'Kargoda', pending: 'Bekliyor', confirmed: 'Onaylandı' },
    auth: { login: 'Giriş Yap', signup: 'Hesap Oluştur', email: 'E-posta', password: 'Şifre', fullName: 'Ad Soyad', passwordPlaceholder: '••••••••', emailPlaceholder: 'ad@ornek.com', signInBtn: 'Giriş Yap', signUpBtn: 'Hesap Oluştur', signingIn: 'Giriş yapılıyor...', creatingAccount: 'Hesap oluşturuluyor...', noAccount: 'Hesabın yok mu?', hasAccount: 'Zaten hesabın var mı?', createAccount: 'Hesap Oluştur', signIn: 'Giriş Yap', tagline: 'Tüm network marketing işini tek akıllı sistemden yönet.' },
  },
} as const

export type TranslationKeys = typeof translations.en
